name: CI for simple website
on: 
  push:
    branches: ["main"]
jobs:
  first-job:
    runs-on: self-hosted
    steps:
    - name: pull code from github to server
      uses: actions/checkout@v4
    - name: check pwd
      run: pwd
